name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies (if necessary)
      run: |
        cd frontend
        npm install  # If you have dependencies in your frontend

    - name: Build the frontend (if necessary)
      run: |
        cd frontend
        npm run build  # Only if you are building assets, e.g., using webpack or similar

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend  # Path to the frontend folder
